-- 015_nhi_drug_lookup.sql
-- 建立健保署藥品代碼對照表，供匯入條碼時回顯中文品名
CREATE TABLE IF NOT EXISTS public.nhi_drug_lookup (
  id          BIGGENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_code   TEXT NOT NULL UNIQUE,
  chinese_name TEXT,
  english_name TEXT,
  created_at  TIMESTAMPZ DEFAULT now(),
  updated_at  TIMESTAMPZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nhi_drug_lookup_drug_code
  ON public.nhi_drug_lookup (drug_code);

CREATE OR REPLACE FUNCTION public.u_nhi_drug_lookup_updated_at ()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_nhi_drug_lookup_updated_at
  ON public.nhi_drug_lookup;

CREATE TRIGGER trg_nhi_drug_lookup_updated_at
BEFORE UPDATE
  ON public.nhi_drug_lookup
FOR EACH ROW
EXECUTE PROCEDURE public.u_nhi_drug_lookup_updated_at ();
