-- 017_refresh_nhi_lookup.sql
-- 建立「健保署藥品對照表」增量匯入狀態表
CREATE TABLE IF NOT EXISTS public.nhi_import_state (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_set_id TEXT NOT NULL DEFAULT 'A21030000I-E41001-001',
  last_line BIGINT NOT NULL DEFAULT 0,
  last_refresh_at TIMESTAMPZ DEFAULT now(),
  finished  BOOLEAN DEFAULT false,
  meta      JSONB DEFAULT '{}'::jsonb,
  UNIQUE (data_set_id)
);